### ISSUE TITLE
redundant links in the navigation menu

### ISSUE THREAD

**Issue by robsmithwashere** [the-pudding/website#155]
The "[How Artists Get Paid from Streaming"](https://pudding.cool/2022/06/streaming/) story, and likely some others, includes the below navigation menu. As a result of last year's site revamp, the first three bulleted links all lead you to the same (home)page. Could we lose the first two? 

<img width="453" alt="Screen Shot 2022-09-02 at 10 42 38 AM" src="https://user-images.githubusercontent.com/88445968/188174522-1969f943-57c3-4c6d-a10c-f7be5c6c41df.png">

**Comment by russellsamora** [comment]
this is actually related to the starter template, so I'm closing this here

**Comment by russellsamora** [comment]
fixed starter template codebase
