### ISSUE TITLE
footer stories design

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/website#175]
in `layout.svelte` do `<Footer topics={true}` and or `Footer recent={true}`- though right now topics is random, recent is last few. we could make it so its always most recent and its just image or text. the images will be different too, so you could just hard code some in to test.

**Comment by jadiehm** [comment]
@russellsamora there are stories on the page when recent is true, but i couldn't figure out how to give them all the properties they needed to render correctly in the story component with the way you are pulling in the data. missing {number, date, short, correct url}. not styled for mobile yet either.

**Comment by russellsamora** [comment]
fixed - we just need to discuss style change/what content can be available IRL
