### ISSUE TITLE
design interstitial card for follows

### ISSUE THREAD

**Issue by russellsamora** [the-pudding/website#205]

**Comment by jadiehm** [comment]
@russellsamora I got started on the designs for these. You'll notice that there are 3 new Svelte files:
- Story.Subscribe.svelte
- Story.Merch.svelte
- Story.Faves.svelte

We could potentially intersperse all of them, especially if 3 things happen:
- You show me how to get our team authors list in the faves on + we go back to our_faves being people's names.
- I do a quick merch spruce before we push the big website update.
- You/ or I (with your guidance) modify your current code to drop them in.

**Comment by russellsamora** [comment]
* done on 1 (new column in sheet)
* ready to go on 3
